"""added calorie intake

Revision ID: fec29946cd59
Revises: 8a26b7a099b9
Create Date: 2023-10-31 12:38:16.611412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec29946cd59'
down_revision = '8a26b7a099b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calorie_intake', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('calorie_intake')

    # ### end Alembic commands ###
